/*Contains EDA queries to analyze the data, including:
  Customer distribution by country & gender.
  Product count and cost analysis by category.
  Revenue by category and customers.
  Top 5 / worst 5 products by revenue.
  Distribution of sales across countries.*/

/*Find the date of the first and last order
  How many years of sales are available*/

SELECT 
MAX(order_date) as max_date,
MIN(order_date) as min_date,
DATEDIFF(year,MAX(order_date),MIN(order_date))
FROM gold.fact_sales

/*Find the youngest and the oldest customer*/
SELECT
MIN(birthdate) as old,
MAX(birthdate) as new,
DATEDIFF(year,MIN(birthdate),MAX(birthdate))
FROM gold.fact_sales

--Find the total sales
SELECT 
SUM(Sales_amount) as TotalSales
FROM gold.fact_sales

-- Find how many items are sold
SELECT
SUM(QUANTITY)
FROM gold.fact_sales

-- Find the average selling price
SELECT
AVG(price) as avg_price
FROM gold.fact_sales

-- Find the total number of orders
SELECT COUNT(order_number) as total_order
FROM gold.fact_sales
SELECT COUNT( distinct order_number) 
FROM gold.fact_sales

--Find the total number of products
SELECT 
COUNT(product_key) as total_products
FROM gold.fact_sales
SELECT 
COUNT(distinct product_key) as total_products
FROM gold.fact_sales

--Find the total number of customers
SELECT 
COUNT(customer_key) as total_products
FROM gold.fact_sales
SELECT 
COUNT(distinct customer_key) as total_products
FROM gold.fact_sales

-- Find total customers by countries
SELECT 
country,
COUNT(customer_key) as customers
FROM gold.dim_customers
GROUP BY country
ORDER BY customers DESC

-- Find total customers by gender
SELECT 
gender,
COUNT(customer_key) as TotalCustomers
FROM gold.dim_customers
GROUP BY GENDER

-- Find total products by category
SELECT 
category,
COUNT(category) as Total
FROM gold.dim_products
GROUP BY category

-- What is the average cost in each category
SELECT 
category,
AVG(cost) as avgCost
FROM gold.dim_products
GROUP BY category
ORDER BY avgCost DESC

-- What is the total revenue generated for each category
SELECT 
p.category,
SUM(s.sales_amount) as TotalRevenue
FROM gold.fact_sales as  s
LEFT JOIN gold.dim_products as p
ON s.product_key = p.product_key
GROUP BY category
ORDER BY TotalRevenue 

-- Find the total revenue generated by each customer
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) as totalSales
FROM gold.fact_sales as s
LEFT JOIN gold.dim_customers as c
ON s.customer_key = c.customer_key
Group BY c.customer_key,c.first_name,c.last_name
ORDER BY totalSales DESC

-- What is the distribution of sold items across countries
SELECT 
gc.country,
gp.category,
SUM(gp.cost)
FROM gold.dim_customers gc
LEFT JOIN gold.dim_products gp
ON gp.product_key = gc.customer_key
GROUP BY gc.country,gp.category
ORDER BY country

-- Which 5 products generate highest revenue
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) as TotalSales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY TotalSales DESC

-- what are the 5 worst-performing products in terms of sales
SELECT TOP 5
p.product_name,
SUM(f.sales_amount) as TotalSales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY TotalSales 

